config/routes.rb
Rails.application.routes.draw do
  get 'page/home'
  resources :grupo_relacao_usuarios
  resources :grupos
  resources :usuarios

  mount ActionCable.server =>'/cable'

  root to: 'usuarios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grupo_relacao_usuario.rb
class GrupoRelacaoUsuario < ApplicationRecord
  belongs_to :usuario
  belongs_to :grupo

end

app/controllers/grupo_relacao_usuarios_controller.rb
class GrupoRelacaoUsuariosController < ApplicationController
  before_action :set_grupo_relacao_usuario, only: %i[ show edit update destroy ]

  # GET /grupo_relacao_usuarios or /grupo_relacao_usuarios.json
  def index
    @grupo_relacao_usuarios = GrupoRelacaoUsuario.all
  end

  # GET /grupo_relacao_usuarios/1 or /grupo_relacao_usuarios/1.json
  def show
  end

  # GET /grupo_relacao_usuarios/new
  def new
    @grupo_relacao_usuario = GrupoRelacaoUsuario.new
    @grupos = session[:grupos]
    @usuarios = Usuario.where.not("id=#{session[:user]['id']}")
  end

  # GET /grupo_relacao_usuarios/1/edit
  def edit
  end

  # POST /grupo_relacao_usuarios or /grupo_relacao_usuarios.json
  def create
    @grupo_relacao_usuario = GrupoRelacaoUsuario.new(grupo_relacao_usuario_params)

    respond_to do |format|
      if @grupo_relacao_usuario.save
        format.html { redirect_to "/usuarios/#{session[:user]['id']}", notice: "Grupo relacao usuario was successfully created." }
        format.json { render :show, status: :created, location: @grupo_relacao_usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grupo_relacao_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupo_relacao_usuarios/1 or /grupo_relacao_usuarios/1.json
  def update
    respond_to do |format|
      if @grupo_relacao_usuario.update(grupo_relacao_usuario_params)
        format.html { redirect_to @grupo_relacao_usuario, notice: "Grupo relacao usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @grupo_relacao_usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grupo_relacao_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupo_relacao_usuarios/1 or /grupo_relacao_usuarios/1.json
  def destroy
    @grupo_relacao_usuario.destroy
    respond_to do |format|
      format.html { redirect_to grupo_relacao_usuarios_url, notice: "Grupo relacao usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo_relacao_usuario
      @grupo_relacao_usuario = GrupoRelacaoUsuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grupo_relacao_usuario_params
      params.require(:grupo_relacao_usuario).permit(:usuario_id, :grupo_id)
    end
end

app/helpers/grupo_relacao_usuarios_helper.rb
module GrupoRelacaoUsuariosHelper
end

app/views/grupo_relacao_usuarios/_form.html.erb
<%= form_with(model: grupo_relacao_usuario, local: true) do |form| %>
  <% if grupo_relacao_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grupo_relacao_usuario.errors.count, "error") %> prohibited this grupo_relacao_usuario from being saved:</h2>

      <ul>
      <% grupo_relacao_usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :grupo_id %>
    <%= form.select :grupo_id, options_for_select(@grupos.map{|grupo| [grupo['nome'],grupo['id']]}) %>
  </div>

<div class="field">
    <%= form.label :usuario_id %>
    <%= form.select :usuario_id, options_for_select(@usuarios.map{|usuario| [usuario['nome'],usuario['id']]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grupo_relacao_usuarios/edit.html.erb
<h1>Editing Grupo Relacao Usuario</h1>

<%= render 'form', grupo_relacao_usuario: @grupo_relacao_usuario %>

<%= link_to 'Show', @grupo_relacao_usuario %> |
<%= link_to 'Back', grupo_relacao_usuarios_path %>

app/views/grupo_relacao_usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupo Relacao Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Grupo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupo_relacao_usuarios.each do |grupo_relacao_usuario| %>
      <tr>
        <td><%= grupo_relacao_usuario.usuario.nome %></td>
        <td><%= grupo_relacao_usuario.grupo.nome %></td>
        <td><%= link_to 'Show', grupo_relacao_usuario %></td>
        <td><%= link_to 'Edit', edit_grupo_relacao_usuario_path(grupo_relacao_usuario) %></td>
        <td><%= link_to 'Destroy', grupo_relacao_usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo Relacao Usuario', new_grupo_relacao_usuario_path %>

app/views/grupo_relacao_usuarios/new.html.erb
<h1>Adicionar usuário no grupo</h1>

<%= render 'form', grupo_relacao_usuario: @grupo_relacao_usuario %>

<%= link_to 'Back', grupo_relacao_usuarios_path %>

app/views/grupo_relacao_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @grupo_relacao_usuario.usuario %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @grupo_relacao_usuario.grupo %>
</p>

<%= link_to 'Edit', edit_grupo_relacao_usuario_path(@grupo_relacao_usuario) %> |
<%= link_to 'Back', grupo_relacao_usuarios_path %>