config/routes.rb
Rails.application.routes.draw do
  get 'page/home'
  resources :grupo_relacao_usuarios
  resources :grupos
  resources :usuarios

  mount ActionCable.server =>'/cable'

  root to: 'usuarios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grupo.rb
class Grupo < ApplicationRecord
  has_many :usuarios
  has_many :grupo_relacao_usuarios, dependent: :delete_all
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: %i[ show edit update destroy ]

  include ApplicationHelper
  # GET /grupos or /grupos.json
  def index
    @grupos = Grupo.all
  end

  # GET /grupos/1 or /grupos/1.json
  def show
    @messages = Mensagem.where("grupo_id=#{@grupo.id}")
    @permisao = GrupoRelacaoUsuario.
      where("grupo_id=#{@grupo.id} ").
      where("usuario_id=#{session[:user]['id']}")

  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
    @relacao = GrupoRelacaoUsuario.new
    @dm = params[:dm]
    @usuarios = Usuario.where.not("id=#{session[:user]['id']}")
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos or /grupos.json
  def create
    @grupo = Grupo.new( {:nome=> grupo_params['nome'], :dm => grupo_params['dm']} )
  
    @usuario = Usuario.find(session[:user]['id'])
    
    @relacao = GrupoRelacaoUsuario.new({:usuario => @usuario,:grupo => @grupo})

    if grupo_params['dm'] == "true"
      @usuario2 = Usuario.find( grupo_params[:usuario_id]) 
      @relacao2 = GrupoRelacaoUsuario.new({ :usuario => @usuario2 , :grupo => @grupo})
      @relacao2.save
    end  

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: "Grupo was successfully created." }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end

    @relacao.save
  

    update_grupos(@usuario.id)
  end

  # PATCH/PUT /grupos/1 or /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: "Grupo was successfully updated." }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1 or /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: "Grupo was successfully destroyed." }
      format.json { head :no_content }
    end
    relacoes_grupos=GrupoRelacaoUsuario.where("usuario_id = #{session[:user]['id']}")
    grupos_do_usuario=[]
    relacoes_grupos.each do|grupo_relacao|
      grupos_do_usuario << Grupo.where("id = #{grupo_relacao.grupo_id}").first()
    end

    session[:grupos] = grupos_do_usuario
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def grupo_params
      params.require(:grupo).permit(:nome,:dm,:usuario_id)
    end
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_with(model: grupo, local: true) do |form| %>
  <% if grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if dm == "true" %>
    <div class="field">
      <%= form.label :usuario %>
      <%= form.select :usuario_id, options_for_select(usuarios.map{|usuario| [usuario.nome,usuario.id]})%>
    </div>

    <div class="field">
      <input value="" type="hidden" name="grupo[nome]" id="grupo_nome">
      <%= form.hidden_field :dm, value: "true" %>
    </div>
  <% else %>

  <div class="field">
      <input value="" type="hidden" name="grupo[nome]" id="grupo_nome">
      <%= form.hidden_field :dm, value: "false" %>
    </div>
  
    <div class="field">
      <%= form.label :nome %>
      <%= form.text_field :nome %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
    <% if dm == "true" %>
      contato = $('#grupo_usuario_id').find(":selected").text()

      $('#grupo_nome').val("<%= session[:user]['nome']%>/" + contato)

      $( "#grupo_usuario_id" ).change(function() {
          contato = $('#grupo_usuario_id').find(":selected").text()
          $('#grupo_nome').val("<%= session[:user]['nome']%>/" + contato)
      });
    <% end %>
</script>

app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form', grupo: @grupo %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.nome %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<h1>New Grupo</h1>

<%= render 'form', {grupo: @grupo,dm:@dm, usuarios: @usuarios} %>

<%= link_to 'Back', grupos_path %>

app/views/grupos/show.html.erb
<% if @permisao.present?%>
  <div align="center" class="container">

    <% nomes = @grupo.nome.split('/') %>
    <% if session[:user]['nome'] == nomes[0] %>
      <h1 class="title"><%=nomes[1]%></h1>
    <% else %>
      <h1 class="title"><%=nomes[0]%></h1>
    <% end %>
      <% if @grupo.dm == false %>
        <a href="/grupo_relacao_usuarios/new"><i class="text-align-right fas fa-user-plus"></i></a>
      <% end %>

    <div id="messages" class="scrollview" style="overflow-y: scroll; height:80vh;background-color: #ececec">
      <%@messages.each do |mensagem| %>
        <%if mensagem.usuario.id == session[:user]['id'] %>
          <p class="alert alert-primary" role="alert"><%=mensagem.usuario.nome + ': ' + mensagem.conteudo %></p>
        <%else %>
          <p class="alert alert-light" role="alert"><%=mensagem.usuario.nome + ': ' + mensagem.conteudo %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <input  id="caixa_de_dialogo" type="text" data-behavior="chat_speaker" placeholder=" Diga alguma coisa :) " style="width: 100%">
  </div>

  <script>
       grupo_id = document.querySelector('head').dataset.grupoId = <%= @grupo.id %>
       document.querySelector('head').dataset.usuarioId = <%= session[:user]['id']%>
           $('.scrollview').scrollTop($('.scrollview')[0].scrollHeight);

       this.App || (this.App = {});

       App.chat = App.cable.subscriptions.create({channel:"RoomChannel", sala: grupo_id }, {
           received: function(data) {
               var objDiv;
               $('#messages').append(data['message']);
               objDiv = document.getElementById("messages");
               return objDiv.scrollTop = objDiv.scrollHeight;
           },
           speak: function(msg, a, g) {
               return this.perform('speak', {
                   message: msg,
                   author: a,
                   group: g
               });
           }
       });
       $(document).on('keypress', '#caixa_de_dialogo', function(event) {
           if (event.keyCode === 13) {
               App.chat.speak(event.target.value, document.querySelector('head').dataset.usuarioId, document.querySelector('head').dataset.grupoId);
               event.target.value = "";
               return event.preventDefault();
           }
       });
  </script>
<% else %>
  <div>
    <h3 > Permissão negada</h3>
  </div>
<% end %>