config/routes.rb
Rails.application.routes.draw do
  get 'page/home'
  resources :grupo_relacao_usuarios
  resources :grupos
  resources :usuarios

  mount ActionCable.server =>'/cable'

  root to: 'usuarios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :grupos
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]
  include ApplicationHelper
  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    session.delete(:user)
    session.delete(:grupos)

  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    session[:user] = @usuario
    cookies.signed[:user] = @usuario.id

    update_grupos(params[:id])

  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Login</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nome %></td>
        <td><%= link_to 'Login', usuario %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar novo Usuario', new_usuario_path %>

<% $ajax %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Bem vindo de volta: <strong><%= @usuario.nome %></strong></h3>

<h5>Para que os outros vejam que você está online você precisa vizualizar um grupo ou conversa,</h5>
<h5>caso não possua crie uma agora :)</h5>